# .github/workflows/ci-cd.yml
name: Python Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t simple-python-docker:latest .
          docker tag simple-python-docker:latest FritzAutomation/simple-python-docker:latest

      # Step 5: Push the Docker image
      - name: Push Docker image
        run: |
          docker push FritzAutomation/simple-python-docker:latest

      # Step 6: Deploy locally (optional)
      # You could SSH into a deployment server or trigger a deployment script here.
